{"type":"PR","pr":{"number":8,"head":"4e0a6c5bfdfb54606dc7288b0b2d9699d5f5261b"},"user":"koh518","status":"pending_publish","branch":"cms/2018-10-15-python3-6-0-matplotlibが仮想環境で動作しない","collection":"post","title":"Python3.6.0 Matplotlibが仮想環境で動作しない","description":"No Description!","objects":{"entry":{"path":"_posts/2018-10-15-python3-6-0-matplotlibが仮想環境で動作しない.md","sha":"783eb9e31e6a6d5cc19c928a12f6ac7c2043ed62"},"files":[]},"timeStamp":"2018-10-14T21:25:08.850Z"}