{"type":"PR","pr":{"number":7,"head":"579efa9802f3be4e58e6a9d754a06d6859cd65ac"},"user":"koh518","status":"draft","branch":"cms/2018-10-15-python3-6-0-matplotlibが仮想環境で動作しない","collection":"post","title":"Python3.6.0 Matplotlibが仮想環境で動作しない","description":"No Description!","objects":{"entry":{"path":"_posts/2018-10-15-python3-6-0-matplotlibが仮想環境で動作しない.md","sha":"063a171578cf4571d34de241d79c830ac26e6854"},"files":[]},"timeStamp":"2018-10-14T21:05:27.813Z"}